# Generated by Django 4.0.3 on 2022-03-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('clinica', models.CharField(blank=True, choices=[('Clinica Sorriso', 'Clinica Sorriso'), ('SEPRI', 'SEPRI')], max_length=100, null=True)),
                ('validade', models.DateField()),
                ('local_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('nib', models.CharField(max_length=100, null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo'), ('Contratado', 'Contratado')], max_length=100)),
                ('nr_bi', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(max_length=100, null=True)),
                ('nuit', models.CharField(max_length=100, null=True)),
                ('inss', models.CharField(max_length=100, null=True)),
                ('data_nascimeto', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colaborador')),
                ('validade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.aso')),
            ],
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botas', models.BooleanField(default=False)),
                ('perneiras', models.BooleanField(default=False)),
                ('capacetes', models.BooleanField(default=False)),
                ('jugulares', models.BooleanField(default=False)),
                ('Abafadores', models.BooleanField(default=False)),
                ('colete', models.BooleanField(default=False)),
                ('refletor', models.BooleanField(default=False)),
                ('oculos_escuros', models.BooleanField(default=False)),
                ('oculos_claros', models.BooleanField(default=False)),
                ('Luvas', models.BooleanField(default=False)),
                ('galochas', models.BooleanField(default=False)),
                ('capas_refletores', models.BooleanField(default=False)),
                ('pasta_plastica', models.BooleanField(default=False)),
                ('lanterna', models.BooleanField(default=False)),
                ('data_recepcao', models.DateTimeField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Cracha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=100)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador')),
                ('validade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.aso')),
            ],
        ),
        migrations.AddField(
            model_name='aso',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador'),
        ),
    ]
