# Generated by Django 4.0.3 on 2022-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_aso_id_alter_colaborador_id_alter_cracha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='status',
            field=models.CharField(blank=True, choices=[('Liberado', 'Liberado'), ('Pendente', 'Pendente')], max_length=100, null=True),
        ),
    ]
