# Generated by Django 4.0.3 on 2022-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
