# Generated by Django 4.0.3 on 2022-03-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aso_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador', to_field='nome'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
