# Generated by Django 4.0.3 on 2022-03-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aso_nome_alter_colaborador_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epi',
            old_name='Abafadores',
            new_name='abafadores',
        ),
        migrations.AddField(
            model_name='epi',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
