# Generated by Django 4.0.3 on 2022-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_abafadores_epi_abafadores_epi_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='data_recepcao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
