# Generated by Django 4.0.3 on 2022-03-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_epi_data_recepcao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epi',
            old_name='capas_refletores',
            new_name='capas_de_chuva_refletores',
        ),
        migrations.RenameField(
            model_name='epi',
            old_name='colete',
            new_name='colete_refletor',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='refletor',
        ),
    ]
