# Generated by Django 4.0.3 on 2022-03-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso',
            name='base',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
