# Generated by Django 4.0.3 on 2022-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aso_realizacao_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aso',
            name='realizacao_exame',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
