# Generated by Django 4.0.3 on 2022-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_epi_luvas_alter_epi_abafadores_alter_epi_botas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
