# Generated by Django 4.0.3 on 2022-03-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_epi_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epi',
            old_name='oculos_claros',
            new_name='oculos_de_protecao',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='oculos_escuros',
        ),
    ]
